GET http://localhost:3000/categories

###

GET http://localhost:3000/categories?title=au

###
POST http://localhost:3000/categories
Content-type: application/json

{
    "title": "immobilier"
}

###
PUT http://localhost:3000/categories/1
Content-Type: application/json

{
    "title": "divers"
}

###
DELETE http://localhost:3000/categories/4